---
default_istio_image_tag: "1.1"
default_istio_namespace: "istio-system"
default_istio_maistra_image_tag: "0.7.0"
default_istio_maistra_image_prefix: "maistra/"
default_istio_productised_image_tag: "0.7.0"
default_istio_productised_image_prefix: "openshift-istio-tech-preview/"
default_istio_jaeger_image_prefix: "jaegertracing/"
default_istio_jaeger_image_tag: "1.9"
default_istio_elasticsearch_image_prefix: "registry.centos.org/rhsyseng/"
default_istio_elasticsearch_image_tag: "5.6.10"
default_istio_jaeger_productised_image_prefix: "distributed-tracing-tech-preview/"
default_istio_jaeger_productised_image_tag: "1.9.0"
default_istio_elasticsearch_productised_image_tag: "5.6.10"
default_istio_kiali_image_prefix: "kiali/"
default_istio_kiali_image_tag: "v0.13.0"
default_istio_kiali_productised_image_prefix: "{{ default_istio_productised_image_prefix }}"
default_istio_kiali_productised_image_tag: "0.13.0"

default_istio_elasticsearch_memory: "1Gi"

default_istio_maistra_component_labels:
  - "app=elasticsearch"
  - "app=jaeger"
  - "app=kiali"

openshift_istio_image_dict:
  origin:
    istio_prefix: "{{ default_istio_maistra_image_prefix }}"
    istio_version: "{{ default_istio_maistra_image_tag }}"
    suffix: "-centos7"
    namespace: "{{ default_istio_namespace }}"
    jaeger_prefix: "{{ default_istio_jaeger_image_prefix }}"
    jaeger_version: "{{ default_istio_jaeger_image_tag }}"
    elasticsearch_version: "{{ default_istio_elasticsearch_image_tag }}"
    kiali_prefix: "{{ default_istio_kiali_image_prefix }}"
    kiali_version: "{{ default_istio_kiali_image_tag }}"
  openshift:
    istio_prefix: "{{ default_istio_productised_image_prefix }}"
    istio_version: "{{ default_istio_productised_image_tag }}"
    suffix: ""
    namespace: "{{ default_istio_namespace }}"
    jaeger_prefix: "{{ default_istio_jaeger_productised_image_prefix }}"
    jaeger_version: "{{ default_istio_jaeger_productised_image_tag }}"
    elasticsearch_version: "{{ default_istio_elasticsearch_productised_image_tag }}"
    kiali_prefix: "{{ default_istio_kiali_productised_image_prefix }}"
    kiali_version: "{{ default_istio_kiali_productised_image_tag }}"

openshift_deployment_type: "origin"

openshift_istio_install: true
openshift_istio_install_community: false
openshift_istio_install_auth: false
openshift_istio_install_launcher: false

openshift_istio_service_accounts:
  - "istio-citadel-service-account"
  - "istio-egressgateway-service-account"
  - "istio-galley-service-account"
  - "istio-ingressgateway-service-account"
  - "istio-mixer-service-account"
  - "istio-pilot-service-account"
  - "istio-sidecar-injector-service-account"

openshift_istio_component_types:
  - "route"
  - "service"
  - "deployment"
  - "daemonset"
  - "statefulset"
  - "imagestream"

openshift_istio_maistra_component_types:
  - "configmap"
  - "clusterrole"
  - "clusterrolebinding"
  - "customresourcedefinition"

openshift_istio_grafana_service_account: "grafana"
openshift_istio_prometheus_service_account: "prometheus"
openshift_istio_jaeger_service_account: "jaeger"
openshift_istio_elasticsearch_service_account: "elasticsearch"
openshift_istio_kiali_service_account: "kiali-service-account"

openshift_istio_additional_scc_service_accounts:
  - "{{ openshift_istio_grafana_service_account }}"
  - "{{ openshift_istio_prometheus_service_account }}"

openshift_istio_additional_scc_privileged_service_accounts:
  - "{{ openshift_istio_jaeger_service_account }}"

openshift_istio_additional_service_accounts:
 - "{{ openshift_istio_grafana_service_account }}"
 - "{{ openshift_istio_prometheus_service_account }}"
 - "{{ openshift_istio_jaeger_service_account }}"
 - "{{ openshift_istio_elasticsearch_service_account }}"
 - "{{ openshift_istio_kiali_service_account }}"

openshift_istio_api_url: "https://{{ ansible_env.KUBERNETES_SERVICE_HOST + ':' + ansible_env.KUBERNETES_SERVICE_PORT }}"

launcher_project_name: devex
launcher_keycloak_url:
launcher_keycloak_realm:
launcher_catalog_git_repo: https://github.com/fabric8-launcher/launcher-booster-catalog.git
launcher_catalog_git_branch: v71
launcher_booster_catalog_filter: booster.mission.metadata.istio

launcher_github_username:
launcher_github_token:
launcher_openshift_user: developer
launcher_openshift_pwd: developer

launcher_backend_image_tag: ab535bc
launcher_frontend_image_tag: 4571dfc
launcher_controller_image_tag: 2.3.7

openshift_istio_install_kiali: true
openshift_istio_kiali_username: ""
openshift_istio_kiali_password: ""
