---

openshift_istio_files: "roles/openshift_istio/files"

openshift_istio_yaml: "{{ openshift_istio_files }}/istio.yaml"
openshift_istio_auth_yaml: "{{ openshift_istio_files }}/istio-auth.yaml"
openshift_istio_crds_yaml: "{{ openshift_istio_files }}/istio-crds.yaml"
openshift_istio_authenticated_clusterrole_yaml: "{{ openshift_istio_files }}/istio-authenticated-clusterrole.yaml"

openshift_grafana_yaml: "{{ openshift_istio_files }}/grafana.yaml"
openshift_jaeger_production_yaml: "{{ openshift_istio_files }}/jaeger-production-template.yml"
openshift_jaeger_tracing_yaml: "{{ openshift_istio_files }}/jaeger-tracing-service.yml"
openshift_jaeger_disable_mtls_yaml: "{{ openshift_istio_files }}/jaeger-disable-mtls.yml"
openshift_elasticsearch_yaml: "{{ openshift_istio_files }}/elasticsearch.yml"
openshift_elasticsearch_configmap_yaml: "{{ openshift_istio_files }}/elasticsearch_configmap.yml"

openshift_kiali_yaml: "{{ openshift_istio_files }}/kiali.yaml"
openshift_istio_kiali_secret: "kiali"

openshift_threescale_yaml: "{{ openshift_istio_files }}/threescale.yaml"
openshift_threescale_adapter_yaml: "{{ openshift_istio_files }}/threescale-adapter.yaml"
openshift_threescale_authorization_template_yaml: "{{ openshift_istio_files }}/threescale-authorization-template.yaml"

launcher_template_yaml: "{{ openshift_istio_files }}/launcher-template.yaml"

openshift_istio_yaml_configuration_files:
  - "{{ openshift_istio_yaml }}"
  - "{{ openshift_istio_auth_yaml }}"

openshift_istio_maistra_version_files:
  - "{{ openshift_grafana_yaml }}"
  - "{{ openshift_istio_yaml }}"
  - "{{ openshift_istio_auth_yaml }}"
  - "{{ openshift_istio_crds_yaml }}"
  - "{{ openshift_istio_authenticated_clusterrole_yaml }}"

openshift_istio_health_check_files:
  - "{{ openshift_istio_yaml }}"
  - "{{ openshift_istio_auth_yaml }}"

openshift_istio_jaeger_yaml_configuration_files:
  - "{{ openshift_jaeger_production_yaml }}"
  - "{{ openshift_elasticsearch_yaml }}"

openshift_istio_kiali_yaml_configuration_files:
  - "{{ openshift_kiali_yaml }}"

openshift_istio_threescale_yaml_configuration_files:
  - "{{ openshift_threescale_yaml }}"

openshift_istio_resources:
  - {name: "rules", namespace: "config.istio.io", version: "v1alpha2"}
  - {name: "attributemanifests", namespace: "config.istio.io", version: "v1alpha2"}
  - {name: "kuberneteses", namespace: "config.istio.io", version: "v1alpha2"}
  - {name: "logentries", namespace: "config.istio.io", version: "v1alpha2"}
  - {name: "metrics", namespace: "config.istio.io", version: "v1alpha2"}
  - {name: "destinationrules", namespace: "networking.istio.io", version: "v1alpha3"}

openshift_istio_secret_query_template: '{range .items[?(@.type=="istio.io/key-and-cert")]}{.metadata.namespace} {.metadata.name}{"\n"}{end}'
