---
# Source: istio/charts/kiali/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console

---
# Source: istio/charts/kiali/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-service-account
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali-v0.4.0
    heritage: Tiller
    release: redhat-0.8.0

---
# Source: istio/charts/kiali/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali
  labels:
    app: kiali
    version: master
rules:
- apiGroups: ["", "apps", "autoscaling"]
  attributeRestrictions: null
  resources:
  - configmaps
  - namespaces
  - nodes
  - pods
  - projects
  - services
  - endpoints
  - deployments
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups: ["route.openshift.io"]
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
- apiGroups: ["config.istio.io"]
  attributeRestrictions: null
  resources:
  - routerules
  - destinationpolicies
  - rules
  - circonuses
  - deniers
  - fluentds
  - kubernetesenvs
  - listcheckers
  - memquotas
  - opas
  - prometheuses
  - rbacs
  - servicecontrols
  - solarwindses
  - stackdrivers
  - statsds
  - stdios
  - apikeys
  - authorizations
  - checknothings
  - kuberneteses
  - listentries
  - logentries
  - metrics
  - quotas
  - reportnothings
  - servicecontrolreports
  verbs:
  - get
  - list
  - watch
- apiGroups: ["networking.istio.io"]
  attributeRestrictions: null
  resources:
  - virtualservices
  - destinationrules
  - gateways
  verbs:
  - get
  - list
  - watch
---
# Source: istio/charts/kiali/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-kiali-admin-role-binding-istio-system
  labels:
    app: kiali
    chart: kiali-v0.4.0
    heritage: Tiller
    release: redhat-0.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali
subjects:
- kind: ServiceAccount
  name: kiali-service-account
  namespace: istio-system

---
# Source: istio/charts/kiali/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 20001
    name: http-kiali
  selector:
    app: kiali

---
# Source: istio/charts/kiali/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    chart: kiali-v0.4.0
    release: redhat-0.8.0
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali
  template:
    metadata:
      name: kiali
      labels:
        app: kiali
    spec:
      serviceAccountName: kiali-service-account

      containers:
      - image: "kiali/kiali:v0.4.0"
        name: kiali
        command:
        - "/opt/kiali/kiali"
        - "-config"
        - "/kiali-configuration/config.yaml"
        - "-v"
        - "4"
        env:
        - name: ACTIVE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVER_CREDENTIALS_USERNAME
          valueFrom:
            secretKeyRef:
              name: kiali
              key: username
        - name: SERVER_CREDENTIALS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kiali
              key: password
        volumeMounts:
        - name: kiali-configuration
          mountPath: "/kiali-configuration"
        resources:
            {}

      volumes:
      - name: kiali-configuration
        configMap:
          name: kiali

---
# Source: istio/charts/kiali/templates/ingress.yaml
