---
- name: Check istio project exists
  command: "{{ openshift_client_binary }} get namespace {{ openshift_istio_namespace }}"
  register: istio_namespace
  ignore_errors: yes

- name: Create istio project if necessary
  command: "{{ openshift_client_binary }} new-project {{ openshift_istio_namespace }}"
  when: istio_namespace.rc != 0

- name: Ensure service accounts have the correct permissions
  include_tasks: setup_service_account.yml
  with_items: "{{ openshift_istio_service_accounts }} + {{ openshift_istio_additional_scc_service_accounts }}"
  loop_control:
    loop_var: service_account

- name: Ensure service accounts are privileged
  include_tasks: setup_privileged_service_account.yml
  with_items: "{{ openshift_istio_additional_scc_privileged_service_accounts }}"
  loop_control:
    loop_var: service_account

- name: Install Istio
  include_tasks: install_istio.yml

- name: Install Grafana
  include_tasks: install_grafana.yml

- name: Install Jaeger
  include_tasks: install_jaeger.yml

- name: Install Kiali
  include_tasks: install_kiali.yml
  when: openshift_istio_install_kiali | bool

- name: Install Launcher
  include_tasks: install_launcher.yml
  when: openshift_istio_install_launcher | bool
